# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all

demo_user = User.create!(username: "John Snow", 
                        personal_email: "test123", 
                        password: "123456",
                        emails: ["test@gmail.com", "test2@gmail.com"],
                        first_name: "john",
                        middle_name: "Boner",
                        last_name: "jones",
                        gender: "M",
                        birthdate: Time.new(2010, 04, 10, 14, 00, 00),
                        phone_number: "973-555-5555",
                        linkedin_url: "linkedin.com/John-Snow-123456",
                        industry: "software engineer",
                        job_title: "lead engineer",
                        job_title_role: "ruler of the pack",
                        job_company_name: "mishanklan industries",
                        job_company_industry: "development",
                        facebook_url: "facebook.com/John-Snow-123456",
                        street_address: "123 hickory lane")

user1 = User.create!(username: "Jonathan Diaz",
                    personal_email: "kingape@gmail.com",
                    password: "123456",
                    emails: ["eXACTLY@gmail.com", "something2@gmail.com"],
                    first_name: "BLING",
                    middle_name: "BLANG",
                    last_name: "BLONG",
                    gender: "F",
                    birthdate: Time.new(1990, 12, 9, 11, 00, 00),
                    phone_number: "973-666-6666",
                    linkedin_url: "linkedin.com/BLING-BLONG-123456",
                    industry: "something else",
                    job_title: "end of the road",
                    job_title_role: "bring it back",
                    job_company_name: "Who am I",
                    job_company_industry: "let's take it back",
                    facebook_url: "facebook.com/BLING-BLANG-123456",
                    street_address: "736 on the block")
                    
user2 = User.create!(username: "Michael Noble",
                    personal_email: "makonobo@gmail.com",
                    password: "123456",
                    emails: ["testing@gmail.com", "test2@yahoo.com"],
                    first_name: "Joey",
                    middle_name: "Coco",
                    last_name: "Diaz",
                    gender: "M",
                    birthdate: Time.new(1965, 04, 10, 14, 00, 00),
                    phone_number: "973-123-4567",
                    linkedin_url: "linkedin.com/Joey-Diaz-123456",
                    industry: "comedian",
                    job_title: "comedy specialist",
                    job_title_role: "funny man",
                    job_company_name: "the comedy cellar",
                    job_company_industry: "comedy",
                    facebook_url: "facebook.com/Joey-Diaz-123456",
                    street_address: "320 East 86th street")

user3 = User.create!(username: "Janette Tinoco",
                    personal_email: "janette@gmail.com",
                    password: "123456",
                    emails: ["something@gmail.com", "i8ateitall@gmail.com", "anothertest@yahoo.com"],
                    first_name: "janette",
                    middle_name: "tinoco",
                    last_name: "jones",
                    gender: "F",
                    birthdate: Time.new(1922, 04, 10, 14, 00, 00),
                    phone_number: "973-444-4444",
                    linkedin_url: "linkedin.com/Janette-Tinoco-123456",
                    industry: "software engineer",
                    job_title: "leader engineer",
                    job_title_role: "ruler of the engineers",
                    job_company_name: "engineer industries",
                    job_company_industry: "ali baba",
                    facebook_url: "facebook.com/Janette-Tinoco-123456",
                    street_address: "Beyond the rainbow")

user4 = User.create!(username: "Alexey Sergieve",
                    personal_email: "alexey@gmail.com",
                    password: "123456",
                    emails: ["test@gmail.com"],
                    first_name: "Alexey",
                    middle_name: "Sergieve",
                    last_name: "Templar",
                    gender: "M",
                    birthdate: Time.new(1987, 04, 10, 14, 00, 00),
                    phone_number: "973-222-2222",
                    linkedin_url: "linkedin.com/Alexey-Sergieve-123456",
                    industry: "fighter man",
                    job_title: "boxer",
                    job_title_role: "Rockey Balboa",
                    job_company_name: "Ryan's belly",
                    job_company_industry: "work harder",
                    facebook_url: "facebook.com/Alexey-Sergieve-123456",
                    street_address: "Somewhere in Ukrainer")